//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickSharp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AboutBackgroundImage {
            get {
                object obj = ResourceManager.GetObject("AboutBackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickSharp Version.
        /// </summary>
        internal static string ClientCopyright1 {
            get {
                return ResourceManager.GetString("ClientCopyright1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2008-2011 Steve Walker.
        /// </summary>
        internal static string ClientCopyright2 {
            get {
                return ResourceManager.GetString("ClientCopyright2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://quicksharp.sourceforge.net.
        /// </summary>
        internal static string ClientCopyright3 {
            get {
                return ResourceManager.GetString("ClientCopyright3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickSharp.
        /// </summary>
        internal static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickSharp.
        /// </summary>
        internal static string ClientTitle {
            get {
                return ResourceManager.GetString("ClientTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon MainFormIcon {
            get {
                object obj = ResourceManager.GetObject("MainFormIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://quicksharp.sourceforge.net/latestversion.txt.
        /// </summary>
        internal static string UpdateCheckURL {
            get {
                return ResourceManager.GetString("UpdateCheckURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://quicksharp.sourceforge.net/.
        /// </summary>
        internal static string UpdateHomeURL {
            get {
                return ResourceManager.GetString("UpdateHomeURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit the QuickSharp Web site for more information.
        /// </summary>
        internal static string UpdateLinkText {
            get {
                return ResourceManager.GetString("UpdateLinkText", resourceCulture);
            }
        }
    }
}
