//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSharp.SqlEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickSharp.SqlEditor.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap DataGrid {
            get {
                object obj = ResourceManager.GetObject("DataGrid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear.
        /// </summary>
        internal static string DataGridMenuClear {
            get {
                return ResourceManager.GetString("DataGridMenuClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Table {0} ({1} {2}).
        /// </summary>
        internal static string DataGridMenuDataTable {
            get {
                return ResourceManager.GetString("DataGridMenuDataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Data to &amp;XML....
        /// </summary>
        internal static string DataGridMenuExportXml {
            get {
                return ResourceManager.GetString("DataGridMenuExportXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save Schema to XSD....
        /// </summary>
        internal static string DataGridMenuExportXsd {
            get {
                return ResourceManager.GetString("DataGridMenuExportXsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rows.
        /// </summary>
        internal static string DataRowsPlural {
            get {
                return ResourceManager.GetString("DataRowsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to row.
        /// </summary>
        internal static string DataRowsSingular {
            get {
                return ResourceManager.GetString("DataRowsSingular", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon DocumentIcon {
            get {
                object obj = ResourceManager.GetObject("DocumentIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ExportDialogTitle {
            get {
                return ResourceManager.GetString("ExportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files (*.xml)|*.xml|All Files (*.*)|*.*.
        /// </summary>
        internal static string ExportDialogXmlFilter {
            get {
                return ResourceManager.GetString("ExportDialogXmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSD Files (*.xsd)|*.xsd|All Files (*.*)|*.*.
        /// </summary>
        internal static string ExportDialogXsdFilter {
            get {
                return ResourceManager.GetString("ExportDialogXsdFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to export.
        /// </summary>
        internal static string ExportErrorMessage {
            get {
                return ResourceManager.GetString("ExportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open.
        /// </summary>
        internal static string OpenErrorMessage {
            get {
                return ResourceManager.GetString("OpenErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OpenErrorTitle {
            get {
                return ResourceManager.GetString("OpenErrorTitle", resourceCulture);
            }
        }
    }
}
