//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSharp.Workspace {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickSharp.Workspace.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Ascx {
            get {
                object obj = ResourceManager.GetObject("Ascx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ashx {
            get {
                object obj = ResourceManager.GetObject("Ashx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Aspx {
            get {
                object obj = ResourceManager.GetObject("Aspx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackupWorkspace {
            get {
                object obj = ResourceManager.GetObject("BackupWorkspace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a new location for the workspace..
        /// </summary>
        internal static string BrowseFolderDialogText {
            get {
                return ResourceManager.GetString("BrowseFolderDialogText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap C {
            get {
                object obj = ResourceManager.GetObject("C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cabinet {
            get {
                object obj = ResourceManager.GetObject("Cabinet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to clone:.
        /// </summary>
        internal static string CloneErrorMessage {
            get {
                return ResourceManager.GetString("CloneErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        internal static string CloneErrorTitle {
            get {
                return ResourceManager.GetString("CloneErrorTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Console {
            get {
                object obj = ResourceManager.GetObject("Console", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to copy:.
        /// </summary>
        internal static string CopyErrorMessage {
            get {
                return ResourceManager.GetString("CopyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyErrorTitle {
            get {
                return ResourceManager.GetString("CopyErrorTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Cpp {
            get {
                object obj = ResourceManager.GetObject("Cpp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CSharp {
            get {
                object obj = ResourceManager.GetObject("CSharp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Css {
            get {
                object obj = ResourceManager.GetObject("Css", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Database {
            get {
                object obj = ResourceManager.GetObject("Database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dbml {
            get {
                object obj = ResourceManager.GetObject("Dbml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete:.
        /// </summary>
        internal static string DeleteErrorMessage {
            get {
                return ResourceManager.GetString("DeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteErrorTitle {
            get {
                return ResourceManager.GetString("DeleteErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}: close all editor instances?.
        /// </summary>
        internal static string DeleteFileOpenMessage {
            get {
                return ResourceManager.GetString("DeleteFileOpenMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Dll {
            get {
                object obj = ResourceManager.GetObject("Dll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Document {
            get {
                object obj = ResourceManager.GetObject("Document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string EnterKey {
            get {
                return ResourceManager.GetString("EnterKey", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Exe {
            get {
                object obj = ResourceManager.GetObject("Exe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Explorer {
            get {
                object obj = ResourceManager.GetObject("Explorer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to launch Windows Explorer:{0}File &quot;{1}&quot; cannot be found..
        /// </summary>
        internal static string ExplorerErrorMessage {
            get {
                return ResourceManager.GetString("ExplorerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Explorer.
        /// </summary>
        internal static string ExplorerErrorTitle {
            get {
                return ResourceManager.GetString("ExplorerErrorTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap H {
            get {
                object obj = ResourceManager.GetObject("H", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Html {
            get {
                object obj = ResourceManager.GetObject("Html", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image {
            get {
                object obj = ResourceManager.GetObject("Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Java {
            get {
                object obj = ResourceManager.GetObject("Java", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Workspace.
        /// </summary>
        internal static string MainViewMenuWorkspace {
            get {
                return ResourceManager.GetString("MainViewMenuWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move:.
        /// </summary>
        internal static string MoveErrorMessage {
            get {
                return ResourceManager.GetString("MoveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string MoveErrorTitle {
            get {
                return ResourceManager.GetString("MoveErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open selected folder:.
        /// </summary>
        internal static string MoveWorkspaceErrorMessage {
            get {
                return ResourceManager.GetString("MoveWorkspaceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string MoveWorkspaceErrorTitle {
            get {
                return ResourceManager.GetString("MoveWorkspaceErrorTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Msil {
            get {
                object obj = ResourceManager.GetObject("Msil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewFolder {
            get {
                object obj = ResourceManager.GetObject("NewFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create folder:.
        /// </summary>
        internal static string NewFolderErrorMessage {
            get {
                return ResourceManager.GetString("NewFolderErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folder.
        /// </summary>
        internal static string NewFolderErrorTitle {
            get {
                return ResourceManager.GetString("NewFolderErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        internal static string NewFolderName {
            get {
                return ResourceManager.GetString("NewFolderName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Obj {
            get {
                object obj = ResourceManager.GetObject("Obj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenFolder {
            get {
                object obj = ResourceManager.GetObject("OpenFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Backup files to this directory:.
        /// </summary>
        internal static string OptionsBackupPathLabel {
            get {
                return ResourceManager.GetString("OptionsBackupPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: the saved path does not exist..
        /// </summary>
        internal static string OptionsBackupPathWarningLabel {
            get {
                return ResourceManager.GetString("OptionsBackupPathWarningLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace.
        /// </summary>
        internal static string OptionsGroupText {
            get {
                return ResourceManager.GetString("OptionsGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace Settings.
        /// </summary>
        internal static string OptionsPageText {
            get {
                return ResourceManager.GetString("OptionsPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;full path in title bar.
        /// </summary>
        internal static string OptionsShowFullPath {
            get {
                return ResourceManager.GetString("OptionsShowFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;hidden files.
        /// </summary>
        internal static string OptionsShowHiddenFiles {
            get {
                return ResourceManager.GetString("OptionsShowHiddenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;system files.
        /// </summary>
        internal static string OptionsShowSystemFiles {
            get {
                return ResourceManager.GetString("OptionsShowSystemFiles", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ParentFolder {
            get {
                object obj = ResourceManager.GetObject("ParentFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pdb {
            get {
                object obj = ResourceManager.GetObject("Pdb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Proj {
            get {
                object obj = ResourceManager.GetObject("Proj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string RenameButtonCancel {
            get {
                return ResourceManager.GetString("RenameButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string RenameButtonOK {
            get {
                return ResourceManager.GetString("RenameButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to rename:.
        /// </summary>
        internal static string RenameErrorMessage {
            get {
                return ResourceManager.GetString("RenameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string RenameErrorTitle {
            get {
                return ResourceManager.GetString("RenameErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name:.
        /// </summary>
        internal static string RenameNewName {
            get {
                return ResourceManager.GetString("RenameNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string RenameTitle {
            get {
                return ResourceManager.GetString("RenameTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Resource {
            get {
                object obj = ResourceManager.GetObject("Resource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Script {
            get {
                object obj = ResourceManager.GetObject("Script", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SearchFolder {
            get {
                object obj = ResourceManager.GetObject("SearchFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to launch Windows shell:{0}File &quot;{1}&quot; cannot be found..
        /// </summary>
        internal static string ShellErrorMessage {
            get {
                return ResourceManager.GetString("ShellErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Shell.
        /// </summary>
        internal static string ShellErrorTitle {
            get {
                return ResourceManager.GetString("ShellErrorTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ShowSourceOnly {
            get {
                object obj = ResourceManager.GetObject("ShowSourceOnly", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sql {
            get {
                object obj = ResourceManager.GetObject("Sql", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Text {
            get {
                object obj = ResourceManager.GetObject("Text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VBNet {
            get {
                object obj = ResourceManager.GetObject("VBNet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create backup.
        /// </summary>
        internal static string WorkspaceBackupDialogError {
            get {
                return ResourceManager.GetString("WorkspaceBackupDialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup is not allowed for entire disk..
        /// </summary>
        internal static string WorkspaceBackupDialogNoDisk {
            get {
                return ResourceManager.GetString("WorkspaceBackupDialogNoDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace backup created successfully.
        /// </summary>
        internal static string WorkspaceBackupDialogSuccess {
            get {
                return ResourceManager.GetString("WorkspaceBackupDialogSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace Backup.
        /// </summary>
        internal static string WorkspaceBackupDialogTitle {
            get {
                return ResourceManager.GetString("WorkspaceBackupDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a location for the backup file..
        /// </summary>
        internal static string WorkspaceBackupFolderMessage {
            get {
                return ResourceManager.GetString("WorkspaceBackupFolderMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon WorkspaceIcon {
            get {
                object obj = ResourceManager.GetObject("WorkspaceIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clone.
        /// </summary>
        internal static string WorkspaceMenuClone {
            get {
                return ResourceManager.GetString("WorkspaceMenuClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create &amp;Folder....
        /// </summary>
        internal static string WorkspaceMenuCreateFolder {
            get {
                return ResourceManager.GetString("WorkspaceMenuCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string WorkspaceMenuDelete {
            get {
                return ResourceManager.GetString("WorkspaceMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Invert Selection.
        /// </summary>
        internal static string WorkspaceMenuInvertSelection {
            get {
                return ResourceManager.GetString("WorkspaceMenuInvertSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Move to Parent Folder.
        /// </summary>
        internal static string WorkspaceMenuMoveToParent {
            get {
                return ResourceManager.GetString("WorkspaceMenuMoveToParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string WorkspaceMenuOpen {
            get {
                return ResourceManager.GetString("WorkspaceMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rename....
        /// </summary>
        internal static string WorkspaceMenuRename {
            get {
                return ResourceManager.GetString("WorkspaceMenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Select Similar.
        /// </summary>
        internal static string WorkspaceMenuSelectSimilar {
            get {
                return ResourceManager.GetString("WorkspaceMenuSelectSimilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folder.
        /// </summary>
        internal static string WorkspaceNewFolder {
            get {
                return ResourceManager.GetString("WorkspaceNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Workspace Files to Zip Archive.
        /// </summary>
        internal static string WorkspaceToolbarBackup {
            get {
                return ResourceManager.GetString("WorkspaceToolbarBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Windows Explorer.
        /// </summary>
        internal static string WorkspaceToolbarLaunchExplorer {
            get {
                return ResourceManager.GetString("WorkspaceToolbarLaunchExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Windows Shell.
        /// </summary>
        internal static string WorkspaceToolbarLaunchShell {
            get {
                return ResourceManager.GetString("WorkspaceToolbarLaunchShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Different Folder as Workspace.
        /// </summary>
        internal static string WorkspaceToolbarOpenFolder {
            get {
                return ResourceManager.GetString("WorkspaceToolbarOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Parent Folder as Workspace.
        /// </summary>
        internal static string WorkspaceToolbarParentFolder {
            get {
                return ResourceManager.GetString("WorkspaceToolbarParentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string WorkspaceToolbarRefresh {
            get {
                return ResourceManager.GetString("WorkspaceToolbarRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Source Files Only.
        /// </summary>
        internal static string WorkspaceToolbarShowSourceOnly {
            get {
                return ResourceManager.GetString("WorkspaceToolbarShowSourceOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace.
        /// </summary>
        internal static string WorkspaceWindowTitle {
            get {
                return ResourceManager.GetString("WorkspaceWindowTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Xaml {
            get {
                object obj = ResourceManager.GetObject("Xaml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Xml {
            get {
                object obj = ResourceManager.GetObject("Xml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Xsd {
            get {
                object obj = ResourceManager.GetObject("Xsd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
