//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSharp.SDKTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickSharp.SDKTools.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Debug {
            get {
                object obj = ResourceManager.GetObject("Debug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Context Help.
        /// </summary>
        internal static string MainHelpMenuContextHelp {
            get {
                return ResourceManager.GetString("MainHelpMenuContextHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help Contents.
        /// </summary>
        internal static string MainHelpMenuHelpContents {
            get {
                return ResourceManager.GetString("MainHelpMenuHelpContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;LR Debugger.
        /// </summary>
        internal static string MainToolsMenuClrDbg {
            get {
                return ResourceManager.GetString("MainToolsMenuClrDbg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;IL Disassembler.
        /// </summary>
        internal static string MainToolsMenuIldasm {
            get {
                return ResourceManager.GetString("MainToolsMenuIldasm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CL&amp;R debugger path:.
        /// </summary>
        internal static string OptionsClrDbgPathLabel {
            get {
                return ResourceManager.GetString("OptionsClrDbgPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: the saved debugger path does not exist..
        /// </summary>
        internal static string OptionsClrDbgPathWarning {
            get {
                return ResourceManager.GetString("OptionsClrDbgPathWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document explorer &amp;arguments:.
        /// </summary>
        internal static string OptionsDexploreArgsLabel {
            get {
                return ResourceManager.GetString("OptionsDexploreArgsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document &amp;explorer path:.
        /// </summary>
        internal static string OptionsDexplorePathLabel {
            get {
                return ResourceManager.GetString("OptionsDexplorePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: the saved document explorer path does not exist..
        /// </summary>
        internal static string OptionsDexplorePathWarning {
            get {
                return ResourceManager.GetString("OptionsDexplorePathWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDK Tools.
        /// </summary>
        internal static string OptionsGroupText {
            get {
                return ResourceManager.GetString("OptionsGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IL &amp;disassembler path:.
        /// </summary>
        internal static string OptionsIldasmPathLabel {
            get {
                return ResourceManager.GetString("OptionsIldasmPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: the saved disassembler path does not exist..
        /// </summary>
        internal static string OptionsIldasmPathWarning {
            get {
                return ResourceManager.GetString("OptionsIldasmPathWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Settings.
        /// </summary>
        internal static string OptionsPageText {
            get {
                return ResourceManager.GetString("OptionsPageText", resourceCulture);
            }
        }
    }
}
