//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSharp.Language.JScript {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickSharp.Language.JScript.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile complete.
        /// </summary>
        internal static string CompileComplete {
            get {
                return ResourceManager.GetString("CompileComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile started.
        /// </summary>
        internal static string CompileStarted {
            get {
                return ResourceManager.GetString("CompileStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft JScript 10.0 Compiler - Debug.
        /// </summary>
        internal static string MicrosoftJS10CompilerD {
            get {
                return ResourceManager.GetString("MicrosoftJS10CompilerD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft JScript 10.0 Compiler - Release.
        /// </summary>
        internal static string MicrosoftJS10CompilerR {
            get {
                return ResourceManager.GetString("MicrosoftJS10CompilerR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft JScript 8.0 Compiler - Debug.
        /// </summary>
        internal static string MicrosoftJS8CompilerD {
            get {
                return ResourceManager.GetString("MicrosoftJS8CompilerD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft JScript 8.0 Compiler - Release.
        /// </summary>
        internal static string MicrosoftJS8CompilerR {
            get {
                return ResourceManager.GetString("MicrosoftJS8CompilerR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft JScript Compiler.
        /// </summary>
        internal static string MicrosoftJSLineParser {
            get {
                return ResourceManager.GetString("MicrosoftJSLineParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Executable (.exe).
        /// </summary>
        internal static string WindowsExe {
            get {
                return ResourceManager.GetString("WindowsExe", resourceCulture);
            }
        }
    }
}
