//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSharp.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickSharp.Tools.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create GUID.
        /// </summary>
        internal static string CreateGuidDialgTitle {
            get {
                return ResourceManager.GetString("CreateGuidDialgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new GUID has been copied to the clipboard..
        /// </summary>
        internal static string CreateGuidDialogMessage {
            get {
                return ResourceManager.GetString("CreateGuidDialogMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Group {
            get {
                object obj = ResourceManager.GetObject("Group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string LibraryHelperCancel {
            get {
                return ResourceManager.GetString("LibraryHelperCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to copy the selected files.
        /// </summary>
        internal static string LibraryHelperCopyErrorMessage {
            get {
                return ResourceManager.GetString("LibraryHelperCopyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickSharp Library Helper.
        /// </summary>
        internal static string LibraryHelperCopyErrorTitle {
            get {
                return ResourceManager.GetString("LibraryHelperCopyErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy QuickSharp files to the workspace..
        /// </summary>
        internal static string LibraryHelperMessage {
            get {
                return ResourceManager.GetString("LibraryHelperMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string LibraryHelperOK {
            get {
                return ResourceManager.GetString("LibraryHelperOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickSharp Library Helper.
        /// </summary>
        internal static string LibraryHelperTitle {
            get {
                return ResourceManager.GetString("LibraryHelperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create &amp;GUID.
        /// </summary>
        internal static string MainToolsMenuCreateGuid {
            get {
                return ResourceManager.GetString("MainToolsMenuCreateGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;QuickSharp Library Helper....
        /// </summary>
        internal static string MainToolsMenuLibraryHelper {
            get {
                return ResourceManager.GetString("MainToolsMenuLibraryHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular E&amp;xpression Helper....
        /// </summary>
        internal static string MainToolsMenuRegexHelper {
            get {
                return ResourceManager.GetString("MainToolsMenuRegexHelper", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Match {
            get {
                object obj = ResourceManager.GetObject("Match", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string RegexDialogButtonClose {
            get {
                return ResourceManager.GetString("RegexDialogButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match.
        /// </summary>
        internal static string RegexDialogButtonMatch {
            get {
                return ResourceManager.GetString("RegexDialogButtonMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression Helper.
        /// </summary>
        internal static string RegexDialogTitle {
            get {
                return ResourceManager.GetString("RegexDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression Error.
        /// </summary>
        internal static string RegexErrorDialogTitle {
            get {
                return ResourceManager.GetString("RegexErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group.
        /// </summary>
        internal static string ResultGroup {
            get {
                return ResourceManager.GetString("ResultGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to groups.
        /// </summary>
        internal static string ResultGroups {
            get {
                return ResourceManager.GetString("ResultGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to match.
        /// </summary>
        internal static string ResultMatch {
            get {
                return ResourceManager.GetString("ResultMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matches.
        /// </summary>
        internal static string ResultMatches {
            get {
                return ResourceManager.GetString("ResultMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string ResultTextLine {
            get {
                return ResourceManager.GetString("ResultTextLine", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
