//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSharp.CodeAssist {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickSharp.CodeAssist.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ASSEMBLY {
            get {
                object obj = ResourceManager.GetObject("ASSEMBLY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CLASS {
            get {
                object obj = ResourceManager.GetObject("CLASS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CLASS_FRIEND {
            get {
                object obj = ResourceManager.GetObject("CLASS_FRIEND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CLASS_PRIVATE {
            get {
                object obj = ResourceManager.GetObject("CLASS_PRIVATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CLASS_PROTECTED {
            get {
                object obj = ResourceManager.GetObject("CLASS_PROTECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CLASS_SEALED {
            get {
                object obj = ResourceManager.GetObject("CLASS_SEALED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CONSTANT {
            get {
                object obj = ResourceManager.GetObject("CONSTANT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CONSTANT_FRIEND {
            get {
                object obj = ResourceManager.GetObject("CONSTANT_FRIEND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CONSTANT_PRIVATE {
            get {
                object obj = ResourceManager.GetObject("CONSTANT_PRIVATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CONSTANT_PROTECTED {
            get {
                object obj = ResourceManager.GetObject("CONSTANT_PROTECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CONSTANT_SEALED {
            get {
                object obj = ResourceManager.GetObject("CONSTANT_SEALED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DELEGATE {
            get {
                object obj = ResourceManager.GetObject("DELEGATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DELEGATE_FRIEND {
            get {
                object obj = ResourceManager.GetObject("DELEGATE_FRIEND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DELEGATE_PRIVATE {
            get {
                object obj = ResourceManager.GetObject("DELEGATE_PRIVATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DELEGATE_PROTECTED {
            get {
                object obj = ResourceManager.GetObject("DELEGATE_PROTECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DELEGATE_SEALED {
            get {
                object obj = ResourceManager.GetObject("DELEGATE_SEALED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ENUM {
            get {
                object obj = ResourceManager.GetObject("ENUM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ENUM_FRIEND {
            get {
                object obj = ResourceManager.GetObject("ENUM_FRIEND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ENUM_PROTECTED {
            get {
                object obj = ResourceManager.GetObject("ENUM_PROTECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ENUM_SEALED {
            get {
                object obj = ResourceManager.GetObject("ENUM_SEALED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EVENT {
            get {
                object obj = ResourceManager.GetObject("EVENT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EVENT_FRIEND {
            get {
                object obj = ResourceManager.GetObject("EVENT_FRIEND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EVENT_PRIVATE {
            get {
                object obj = ResourceManager.GetObject("EVENT_PRIVATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EVENT_PROTECTED {
            get {
                object obj = ResourceManager.GetObject("EVENT_PROTECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EVENT_SEALED {
            get {
                object obj = ResourceManager.GetObject("EVENT_SEALED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EXCEPTION {
            get {
                object obj = ResourceManager.GetObject("EXCEPTION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EXCEPTION_FRIEND {
            get {
                object obj = ResourceManager.GetObject("EXCEPTION_FRIEND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EXCEPTION_PRIVATE {
            get {
                object obj = ResourceManager.GetObject("EXCEPTION_PRIVATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EXCEPTION_PROTECTED {
            get {
                object obj = ResourceManager.GetObject("EXCEPTION_PROTECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EXCEPTION_SEALED {
            get {
                object obj = ResourceManager.GetObject("EXCEPTION_SEALED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FIELD {
            get {
                object obj = ResourceManager.GetObject("FIELD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FIELD_ALIAS {
            get {
                object obj = ResourceManager.GetObject("FIELD_ALIAS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FIELD_FRIEND {
            get {
                object obj = ResourceManager.GetObject("FIELD_FRIEND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FIELD_PRIVATE {
            get {
                object obj = ResourceManager.GetObject("FIELD_PRIVATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FIELD_PROTECTED {
            get {
                object obj = ResourceManager.GetObject("FIELD_PROTECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FIELD_SEALED {
            get {
                object obj = ResourceManager.GetObject("FIELD_SEALED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FILE_REF {
            get {
                object obj = ResourceManager.GetObject("FILE_REF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INTERFACE {
            get {
                object obj = ResourceManager.GetObject("INTERFACE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INTERFACE_FRIEND {
            get {
                object obj = ResourceManager.GetObject("INTERFACE_FRIEND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INTERFACE_PRIVATE {
            get {
                object obj = ResourceManager.GetObject("INTERFACE_PRIVATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INTERFACE_PROTECTED {
            get {
                object obj = ResourceManager.GetObject("INTERFACE_PROTECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INTERFACE_SEALED {
            get {
                object obj = ResourceManager.GetObject("INTERFACE_SEALED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co&amp;de Assist.
        /// </summary>
        internal static string MainEditMenuCodeAssist {
            get {
                return ResourceManager.GetString("MainEditMenuCodeAssist", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap METHOD {
            get {
                object obj = ResourceManager.GetObject("METHOD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap METHOD_EXTENSION {
            get {
                object obj = ResourceManager.GetObject("METHOD_EXTENSION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap METHOD_FRIEND {
            get {
                object obj = ResourceManager.GetObject("METHOD_FRIEND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap METHOD_PRIVATE {
            get {
                object obj = ResourceManager.GetObject("METHOD_PRIVATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap METHOD_PROTECTED {
            get {
                object obj = ResourceManager.GetObject("METHOD_PROTECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap METHOD_SEALED {
            get {
                object obj = ResourceManager.GetObject("METHOD_SEALED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap METHODOVERLOAD {
            get {
                object obj = ResourceManager.GetObject("METHODOVERLOAD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap METHODOVERLOAD_FRIEND {
            get {
                object obj = ResourceManager.GetObject("METHODOVERLOAD_FRIEND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap METHODOVERLOAD_PRIVATE {
            get {
                object obj = ResourceManager.GetObject("METHODOVERLOAD_PRIVATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap METHODOVERLOAD_PROTECTED {
            get {
                object obj = ResourceManager.GetObject("METHODOVERLOAD_PROTECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap METHODOVERLOAD_SEALED {
            get {
                object obj = ResourceManager.GetObject("METHODOVERLOAD_SEALED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NAMESPACE {
            get {
                object obj = ResourceManager.GetObject("NAMESPACE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NAMESPACE_FRIEND {
            get {
                object obj = ResourceManager.GetObject("NAMESPACE_FRIEND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NAMESPACE_PRIVATE {
            get {
                object obj = ResourceManager.GetObject("NAMESPACE_PRIVATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NAMESPACE_PROTECTED {
            get {
                object obj = ResourceManager.GetObject("NAMESPACE_PROTECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NAMESPACE_SEALED {
            get {
                object obj = ResourceManager.GetObject("NAMESPACE_SEALED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OPERATOR {
            get {
                object obj = ResourceManager.GetObject("OPERATOR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OPERATOR_FRIEND {
            get {
                object obj = ResourceManager.GetObject("OPERATOR_FRIEND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OPERATOR_PRIVATE {
            get {
                object obj = ResourceManager.GetObject("OPERATOR_PRIVATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OPERATOR_PROTECTED {
            get {
                object obj = ResourceManager.GetObject("OPERATOR_PROTECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OPERATOR_SEALED {
            get {
                object obj = ResourceManager.GetObject("OPERATOR_SEALED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PROPERTIES {
            get {
                object obj = ResourceManager.GetObject("PROPERTIES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PROPERTIES_FRIEND {
            get {
                object obj = ResourceManager.GetObject("PROPERTIES_FRIEND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PROPERTIES_PRIVATE {
            get {
                object obj = ResourceManager.GetObject("PROPERTIES_PRIVATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PROPERTIES_PROTECTED {
            get {
                object obj = ResourceManager.GetObject("PROPERTIES_PROTECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PROPERTIES_SEALED {
            get {
                object obj = ResourceManager.GetObject("PROPERTIES_SEALED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STRUCTURE {
            get {
                object obj = ResourceManager.GetObject("STRUCTURE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STRUCTURE_FRIEND {
            get {
                object obj = ResourceManager.GetObject("STRUCTURE_FRIEND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STRUCTURE_PRIVATE {
            get {
                object obj = ResourceManager.GetObject("STRUCTURE_PRIVATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STRUCTURE_PROTECTED {
            get {
                object obj = ResourceManager.GetObject("STRUCTURE_PROTECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STRUCTURE_SEALED {
            get {
                object obj = ResourceManager.GetObject("STRUCTURE_SEALED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codeassistdiagnostic.
        /// </summary>
        internal static string SwitchDiagnostic {
            get {
                return ResourceManager.GetString("SwitchDiagnostic", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap TABLE {
            get {
                object obj = ResourceManager.GetObject("TABLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TABLE_ALIAS {
            get {
                object obj = ResourceManager.GetObject("TABLE_ALIAS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TEMPLATE {
            get {
                object obj = ResourceManager.GetObject("TEMPLATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TEMPLATE_FRIEND {
            get {
                object obj = ResourceManager.GetObject("TEMPLATE_FRIEND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TEMPLATE_PRIVATE {
            get {
                object obj = ResourceManager.GetObject("TEMPLATE_PRIVATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TEMPLATE_PROTECTED {
            get {
                object obj = ResourceManager.GetObject("TEMPLATE_PROTECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TEMPLATE_SEALED {
            get {
                object obj = ResourceManager.GetObject("TEMPLATE_SEALED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TYPE {
            get {
                object obj = ResourceManager.GetObject("TYPE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TYPE_FRIEND {
            get {
                object obj = ResourceManager.GetObject("TYPE_FRIEND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TYPE_PRIVATE {
            get {
                object obj = ResourceManager.GetObject("TYPE_PRIVATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TYPE_PROTECTED {
            get {
                object obj = ResourceManager.GetObject("TYPE_PROTECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TYPE_SEALED {
            get {
                object obj = ResourceManager.GetObject("TYPE_SEALED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TYPEDEF {
            get {
                object obj = ResourceManager.GetObject("TYPEDEF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TYPEDEF_FRIEND {
            get {
                object obj = ResourceManager.GetObject("TYPEDEF_FRIEND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TYPEDEF_PRIVATE {
            get {
                object obj = ResourceManager.GetObject("TYPEDEF_PRIVATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TYPEDEF_PROTECTED {
            get {
                object obj = ResourceManager.GetObject("TYPEDEF_PROTECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TYPEDEF_SEALED {
            get {
                object obj = ResourceManager.GetObject("TYPEDEF_SEALED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UNION {
            get {
                object obj = ResourceManager.GetObject("UNION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UNION_FRIEND {
            get {
                object obj = ResourceManager.GetObject("UNION_FRIEND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UNION_PRIVATE {
            get {
                object obj = ResourceManager.GetObject("UNION_PRIVATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UNION_PROTECTED {
            get {
                object obj = ResourceManager.GetObject("UNION_PROTECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UNION_SEALED {
            get {
                object obj = ResourceManager.GetObject("UNION_SEALED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VALUETYPE {
            get {
                object obj = ResourceManager.GetObject("VALUETYPE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VALUETYPE_FRIEND {
            get {
                object obj = ResourceManager.GetObject("VALUETYPE_FRIEND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VALUETYPE_PRIVATE {
            get {
                object obj = ResourceManager.GetObject("VALUETYPE_PRIVATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VALUETYPE_PROTECTED {
            get {
                object obj = ResourceManager.GetObject("VALUETYPE_PROTECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VALUETYPE_SEALED {
            get {
                object obj = ResourceManager.GetObject("VALUETYPE_SEALED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VIEW {
            get {
                object obj = ResourceManager.GetObject("VIEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VIEW_ALIAS {
            get {
                object obj = ResourceManager.GetObject("VIEW_ALIAS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WEBCONTROL {
            get {
                object obj = ResourceManager.GetObject("WEBCONTROL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
