//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSharp.FindInFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickSharp.FindInFiles.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string FindDialogButtonClose {
            get {
                return ResourceManager.GetString("FindDialogButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string FindDialogButtonFind {
            get {
                return ResourceManager.GetString("FindDialogButtonFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string FindDialogButtonReplace {
            get {
                return ResourceManager.GetString("FindDialogButtonReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find in Files.
        /// </summary>
        internal static string FindDialogFindTitle {
            get {
                return ResourceManager.GetString("FindDialogFindTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Find what:.
        /// </summary>
        internal static string FindDialogFindWhat {
            get {
                return ResourceManager.GetString("FindDialogFindWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Look in:.
        /// </summary>
        internal static string FindDialogLookIn {
            get {
                return ResourceManager.GetString("FindDialogLookIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Match case.
        /// </summary>
        internal static string FindDialogMatchCase {
            get {
                return ResourceManager.GetString("FindDialogMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace in Files.
        /// </summary>
        internal static string FindDialogReplaceTitle {
            get {
                return ResourceManager.GetString("FindDialogReplaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Replace with:.
        /// </summary>
        internal static string FindDialogReplaceWith {
            get {
                return ResourceManager.GetString("FindDialogReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Search subfolders.
        /// </summary>
        internal static string FindDialogSearchSubFolders {
            get {
                return ResourceManager.GetString("FindDialogSearchSubFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Use regular expression.
        /// </summary>
        internal static string FindDialogUseRegularExpression {
            get {
                return ResourceManager.GetString("FindDialogUseRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string FindError {
            get {
                return ResourceManager.GetString("FindError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} matches found.
        /// </summary>
        internal static string FindMessageMatchCountMulti {
            get {
                return ResourceManager.GetString("FindMessageMatchCountMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} match found.
        /// </summary>
        internal static string FindMessageMatchCountSingle {
            get {
                return ResourceManager.GetString("FindMessageMatchCountSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching files found.
        /// </summary>
        internal static string FindMessageNoMatchingFiles {
            get {
                return ResourceManager.GetString("FindMessageNoMatchingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files updated.
        /// </summary>
        internal static string FindMessageReplaceCountMulti {
            get {
                return ResourceManager.GetString("FindMessageReplaceCountMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file updated.
        /// </summary>
        internal static string FindMessageReplaceCountSingle {
            get {
                return ResourceManager.GetString("FindMessageReplaceCountSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find i&amp;n Files....
        /// </summary>
        internal static string MainEditMenuFindInFiles {
            get {
                return ResourceManager.GetString("MainEditMenuFindInFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace &amp;in Files....
        /// </summary>
        internal static string MainEditMenuReplaceInFiles {
            get {
                return ResourceManager.GetString("MainEditMenuReplaceInFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output - Find in Files: {0}.
        /// </summary>
        internal static string OutputTitleFind {
            get {
                return ResourceManager.GetString("OutputTitleFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output - Replace in Files: {0}.
        /// </summary>
        internal static string OutputTitleReplace {
            get {
                return ResourceManager.GetString("OutputTitleReplace", resourceCulture);
            }
        }
    }
}
