//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSharp.DocumentTemplates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickSharp.DocumentTemplates.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New From &amp;Template.
        /// </summary>
        internal static string MainFileMenuNewFromTemplate {
            get {
                return ResourceManager.GetString("MainFileMenuNewFromTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string NewFileFormCancel {
            get {
                return ResourceManager.GetString("NewFileFormCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Enter a name for the new item:.
        /// </summary>
        internal static string NewFileFormFilenameLabel {
            get {
                return ResourceManager.GetString("NewFileFormFilenameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string NewFileFormOK {
            get {
                return ResourceManager.GetString("NewFileFormOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New From Template.
        /// </summary>
        internal static string NewFileFormTitle {
            get {
                return ResourceManager.GetString("NewFileFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update template content:.
        /// </summary>
        internal static string TemplateContentUpdateError {
            get {
                return ResourceManager.GetString("TemplateContentUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New From Template.
        /// </summary>
        internal static string TemplateCreationError {
            get {
                return ResourceManager.GetString("TemplateCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to rename file template:.
        /// </summary>
        internal static string TemplateFileRenameError {
            get {
                return ResourceManager.GetString("TemplateFileRenameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template file not found:.
        /// </summary>
        internal static string TemplateNotFound {
            get {
                return ResourceManager.GetString("TemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This template will create new files in the workspace.
        /// </summary>
        internal static string TemplateOverwriteWarningMessage1 {
            get {
                return ResourceManager.GetString("TemplateOverwriteWarningMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and could overwrite existing files without warning..
        /// </summary>
        internal static string TemplateOverwriteWarningMessage2 {
            get {
                return ResourceManager.GetString("TemplateOverwriteWarningMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        internal static string TemplateOverwriteWarningMessage3 {
            get {
                return ResourceManager.GetString("TemplateOverwriteWarningMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string TemplateOverwriteWarningTitle {
            get {
                return ResourceManager.GetString("TemplateOverwriteWarningTitle", resourceCulture);
            }
        }
    }
}
