//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSharp.Explorer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickSharp.Explorer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Ascx {
            get {
                object obj = ResourceManager.GetObject("Ascx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ashx {
            get {
                object obj = ResourceManager.GetObject("Ashx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Aspx {
            get {
                object obj = ResourceManager.GetObject("Aspx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create backup.
        /// </summary>
        internal static string BackupDialogError {
            get {
                return ResourceManager.GetString("BackupDialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup is not allowed for entire disk..
        /// </summary>
        internal static string BackupDialogNoDisk {
            get {
                return ResourceManager.GetString("BackupDialogNoDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer backup created successfully.
        /// </summary>
        internal static string BackupDialogSuccess {
            get {
                return ResourceManager.GetString("BackupDialogSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Backup.
        /// </summary>
        internal static string BackupDialogTitle {
            get {
                return ResourceManager.GetString("BackupDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a location for the backup file..
        /// </summary>
        internal static string BackupFolderMessage {
            get {
                return ResourceManager.GetString("BackupFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a new location for the root folder..
        /// </summary>
        internal static string BrowseFolderDialogText {
            get {
                return ResourceManager.GetString("BrowseFolderDialogText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap C {
            get {
                object obj = ResourceManager.GetObject("C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cabinet {
            get {
                object obj = ResourceManager.GetObject("Cabinet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of {0}.
        /// </summary>
        internal static string CloneCopyName {
            get {
                return ResourceManager.GetString("CloneCopyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to clone:.
        /// </summary>
        internal static string CloneErrorMessage {
            get {
                return ResourceManager.GetString("CloneErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        internal static string CloneErrorTitle {
            get {
                return ResourceManager.GetString("CloneErrorTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ClosedFolder {
            get {
                object obj = ResourceManager.GetObject("ClosedFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Console {
            get {
                object obj = ResourceManager.GetObject("Console", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to copy:.
        /// </summary>
        internal static string CopyErrorMessage {
            get {
                return ResourceManager.GetString("CopyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyErrorTitle {
            get {
                return ResourceManager.GetString("CopyErrorTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Cpp {
            get {
                object obj = ResourceManager.GetObject("Cpp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folder.
        /// </summary>
        internal static string CreateFolderTitle {
            get {
                return ResourceManager.GetString("CreateFolderTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CSharp {
            get {
                object obj = ResourceManager.GetObject("CSharp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Css {
            get {
                object obj = ResourceManager.GetObject("Css", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Database {
            get {
                object obj = ResourceManager.GetObject("Database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dbml {
            get {
                object obj = ResourceManager.GetObject("Dbml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete:.
        /// </summary>
        internal static string DeleteErrorMessage {
            get {
                return ResourceManager.GetString("DeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteErrorTitle {
            get {
                return ResourceManager.GetString("DeleteErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}: close all editor instances?.
        /// </summary>
        internal static string DeleteFileOpenMessage {
            get {
                return ResourceManager.GetString("DeleteFileOpenMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Dll {
            get {
                object obj = ResourceManager.GetObject("Dll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Document {
            get {
                object obj = ResourceManager.GetObject("Document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string EnterKey {
            get {
                return ResourceManager.GetString("EnterKey", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Exe {
            get {
                object obj = ResourceManager.GetObject("Exe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Explorer {
            get {
                object obj = ResourceManager.GetObject("Explorer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon ExplorerIcon {
            get {
                object obj = ResourceManager.GetObject("ExplorerIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        internal static string ExplorerWindowTitle {
            get {
                return ResourceManager.GetString("ExplorerWindowTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FileBackup {
            get {
                object obj = ResourceManager.GetObject("FileBackup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}?.
        /// </summary>
        internal static string FilterDeleteMessage {
            get {
                return ResourceManager.GetString("FilterDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string FilterDeleteTitle {
            get {
                return ResourceManager.GetString("FilterDeleteTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FilterFiles {
            get {
                object obj = ResourceManager.GetObject("FilterFiles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string FilterFormCancel {
            get {
                return ResourceManager.GetString("FilterFormCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Filter patterns:.
        /// </summary>
        internal static string FilterFormFilterLabel {
            get {
                return ResourceManager.GetString("FilterFormFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter &amp;name:.
        /// </summary>
        internal static string FilterFormNameLabel {
            get {
                return ResourceManager.GetString("FilterFormNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string FilterFormOK {
            get {
                return ResourceManager.GetString("FilterFormOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name Filter.
        /// </summary>
        internal static string FilterFormTitle {
            get {
                return ResourceManager.GetString("FilterFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clone.
        /// </summary>
        internal static string FilterMenuClone {
            get {
                return ResourceManager.GetString("FilterMenuClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string FilterMenuDelete {
            get {
                return ResourceManager.GetString("FilterMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit....
        /// </summary>
        internal static string FilterMenuEdit {
            get {
                return ResourceManager.GetString("FilterMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New....
        /// </summary>
        internal static string FilterMenuNew {
            get {
                return ResourceManager.GetString("FilterMenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in file name filter pattern.
        /// </summary>
        internal static string FilterRegexErrorMessage {
            get {
                return ResourceManager.GetString("FilterRegexErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name Filter Error.
        /// </summary>
        internal static string FilterRegexErrorTitle {
            get {
                return ResourceManager.GetString("FilterRegexErrorTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap H {
            get {
                object obj = ResourceManager.GetObject("H", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Html {
            get {
                object obj = ResourceManager.GetObject("Html", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image {
            get {
                object obj = ResourceManager.GetObject("Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Java {
            get {
                object obj = ResourceManager.GetObject("Java", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to launch Windows Explorer:{0}File &quot;{1}&quot; cannot be found..
        /// </summary>
        internal static string LaunchExplorerErrorMessage {
            get {
                return ResourceManager.GetString("LaunchExplorerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Explorer.
        /// </summary>
        internal static string LaunchExplorerErrorTitle {
            get {
                return ResourceManager.GetString("LaunchExplorerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to launch Windows shell:{0}File &quot;{1}&quot; cannot be found..
        /// </summary>
        internal static string LaunchShellErrorMessage {
            get {
                return ResourceManager.GetString("LaunchShellErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Shell.
        /// </summary>
        internal static string LaunchShellErrorTitle {
            get {
                return ResourceManager.GetString("LaunchShellErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Patterns.
        /// </summary>
        internal static string ListViewFilterColumn {
            get {
                return ResourceManager.GetString("ListViewFilterColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Name.
        /// </summary>
        internal static string ListViewNameColumn {
            get {
                return ResourceManager.GetString("ListViewNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Explorer.
        /// </summary>
        internal static string MainViewMenuExplorer {
            get {
                return ResourceManager.GetString("MainViewMenuExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move:.
        /// </summary>
        internal static string MoveErrorMessage {
            get {
                return ResourceManager.GetString("MoveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string MoveErrorTitle {
            get {
                return ResourceManager.GetString("MoveErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open selected folder:.
        /// </summary>
        internal static string MoveRootErrorMessage {
            get {
                return ResourceManager.GetString("MoveRootErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string MoveRootErrorTitle {
            get {
                return ResourceManager.GetString("MoveRootErrorTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Msil {
            get {
                object obj = ResourceManager.GetObject("Msil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewFolder {
            get {
                object obj = ResourceManager.GetObject("NewFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create folder:.
        /// </summary>
        internal static string NewFolderErrorMessage {
            get {
                return ResourceManager.GetString("NewFolderErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folder.
        /// </summary>
        internal static string NewFolderErrorTitle {
            get {
                return ResourceManager.GetString("NewFolderErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        internal static string NewFolderName {
            get {
                return ResourceManager.GetString("NewFolderName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Obj {
            get {
                object obj = ResourceManager.GetObject("Obj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenedFolder {
            get {
                object obj = ResourceManager.GetObject("OpenedFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenFolder {
            get {
                object obj = ResourceManager.GetObject("OpenFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Backup files to this directory:.
        /// </summary>
        internal static string OptionsBackupDirectoryLabel {
            get {
                return ResourceManager.GetString("OptionsBackupDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: the saved path does not exist..
        /// </summary>
        internal static string OptionsBackupDirectoryWarningLabel {
            get {
                return ResourceManager.GetString("OptionsBackupDirectoryWarningLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        internal static string OptionsGroupText {
            get {
                return ResourceManager.GetString("OptionsGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Settings.
        /// </summary>
        internal static string OptionsPageTextExplorer {
            get {
                return ResourceManager.GetString("OptionsPageTextExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name Filters.
        /// </summary>
        internal static string OptionsPageTextFilters {
            get {
                return ResourceManager.GetString("OptionsPageTextFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;full path in title bar.
        /// </summary>
        internal static string OptionsShowFullPath {
            get {
                return ResourceManager.GetString("OptionsShowFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;hidden files.
        /// </summary>
        internal static string OptionsShowHiddenFiles {
            get {
                return ResourceManager.GetString("OptionsShowHiddenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;system files.
        /// </summary>
        internal static string OptionsShowSystemFiles {
            get {
                return ResourceManager.GetString("OptionsShowSystemFiles", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ParentFolder {
            get {
                object obj = ResourceManager.GetObject("ParentFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pdb {
            get {
                object obj = ResourceManager.GetObject("Pdb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Proj {
            get {
                object obj = ResourceManager.GetObject("Proj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string RenameButtonCancel {
            get {
                return ResourceManager.GetString("RenameButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string RenameButtonOK {
            get {
                return ResourceManager.GetString("RenameButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to rename:.
        /// </summary>
        internal static string RenameErrorMessage {
            get {
                return ResourceManager.GetString("RenameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string RenameErrorTitle {
            get {
                return ResourceManager.GetString("RenameErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name:.
        /// </summary>
        internal static string RenameNewName {
            get {
                return ResourceManager.GetString("RenameNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string RenameTitle {
            get {
                return ResourceManager.GetString("RenameTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Resource {
            get {
                object obj = ResourceManager.GetObject("Resource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Script {
            get {
                object obj = ResourceManager.GetObject("Script", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sql {
            get {
                object obj = ResourceManager.GetObject("Sql", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Text {
            get {
                object obj = ResourceManager.GetObject("Text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Explorer Files to Zip Archive.
        /// </summary>
        internal static string ToolbarBackup {
            get {
                return ResourceManager.GetString("ToolbarBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply File Name Filter.
        /// </summary>
        internal static string ToolbarFilter {
            get {
                return ResourceManager.GetString("ToolbarFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Windows Explorer.
        /// </summary>
        internal static string ToolbarLaunchExplorer {
            get {
                return ResourceManager.GetString("ToolbarLaunchExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Windows Shell.
        /// </summary>
        internal static string ToolbarLaunchShell {
            get {
                return ResourceManager.GetString("ToolbarLaunchShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Different Folder as Root Directory.
        /// </summary>
        internal static string ToolbarMoveRoot {
            get {
                return ResourceManager.GetString("ToolbarMoveRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Parent Folder as Root Directory.
        /// </summary>
        internal static string ToolbarParentFolder {
            get {
                return ResourceManager.GetString("ToolbarParentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string ToolbarRefresh {
            get {
                return ResourceManager.GetString("ToolbarRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clone.
        /// </summary>
        internal static string TreeMenuClone {
            get {
                return ResourceManager.GetString("TreeMenuClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create Folder....
        /// </summary>
        internal static string TreeMenuCreateFolder {
            get {
                return ResourceManager.GetString("TreeMenuCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string TreeMenuDelete {
            get {
                return ResourceManager.GetString("TreeMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string TreeMenuOpen {
            get {
                return ResourceManager.GetString("TreeMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rename....
        /// </summary>
        internal static string TreeMenuRename {
            get {
                return ResourceManager.GetString("TreeMenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Set as Current Directory.
        /// </summary>
        internal static string TreeMenuSetAsCurrentDir {
            get {
                return ResourceManager.GetString("TreeMenuSetAsCurrentDir", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap VBNet {
            get {
                object obj = ResourceManager.GetObject("VBNet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Xaml {
            get {
                object obj = ResourceManager.GetObject("Xaml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Xml {
            get {
                object obj = ResourceManager.GetObject("Xml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Xsd {
            get {
                object obj = ResourceManager.GetObject("Xsd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
