//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSharp.Editor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickSharp.Editor.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cut {
            get {
                object obj = ResourceManager.GetObject("Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has been modified outside of the editor..
        /// </summary>
        internal static string FileChangedMessage {
            get {
                return ResourceManager.GetString("FileChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to overwrite the newer version?.
        /// </summary>
        internal static string FileChangedOverwriteMessage {
            get {
                return ResourceManager.GetString("FileChangedOverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reload it?.
        /// </summary>
        internal static string FileChangedReloadMessage {
            get {
                return ResourceManager.GetString("FileChangedReloadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Modified.
        /// </summary>
        internal static string FileChangedTitle {
            get {
                return ResourceManager.GetString("FileChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has a timestamp from the future.
        /// </summary>
        internal static string FileFutureDateMessage1 {
            get {
                return ResourceManager.GetString("FileFutureDateMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overwrite the file to prevent repeated modification warnings..
        /// </summary>
        internal static string FileFutureDateMessage2 {
            get {
                return ResourceManager.GetString("FileFutureDateMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporal Anomaly.
        /// </summary>
        internal static string FileFutureDateTitle {
            get {
                return ResourceManager.GetString("FileFutureDateTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Find {
            get {
                object obj = ResourceManager.GetObject("Find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string FindDialogButtonClose {
            get {
                return ResourceManager.GetString("FindDialogButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        internal static string FindDialogButtonFind {
            get {
                return ResourceManager.GetString("FindDialogButtonFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find All.
        /// </summary>
        internal static string FindDialogButtonFindAllFind {
            get {
                return ResourceManager.GetString("FindDialogButtonFindAllFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace All.
        /// </summary>
        internal static string FindDialogButtonFindAllReplace {
            get {
                return ResourceManager.GetString("FindDialogButtonFindAllReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Next.
        /// </summary>
        internal static string FindDialogButtonReplace {
            get {
                return ResourceManager.GetString("FindDialogButtonReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search operation failed.
        /// </summary>
        internal static string FindDialogExceptionMessage {
            get {
                return ResourceManager.GetString("FindDialogExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Find what:.
        /// </summary>
        internal static string FindDialogFindWhat {
            get {
                return ResourceManager.GetString("FindDialogFindWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Match case.
        /// </summary>
        internal static string FindDialogMatchCase {
            get {
                return ResourceManager.GetString("FindDialogMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current document cannot be searched..
        /// </summary>
        internal static string FindDialogMessageCantSearch {
            get {
                return ResourceManager.GetString("FindDialogMessageCantSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found the search term on {0} lines..
        /// </summary>
        internal static string FindDialogMessageFoundMulti {
            get {
                return ResourceManager.GetString("FindDialogMessageFoundMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found the search term on {0} line..
        /// </summary>
        internal static string FindDialogMessageFoundSingle {
            get {
                return ResourceManager.GetString("FindDialogMessageFoundSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search term could not be found..
        /// </summary>
        internal static string FindDialogMessageNotFound {
            get {
                return ResourceManager.GetString("FindDialogMessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced the search term on {0} lines..
        /// </summary>
        internal static string FindDialogMessageReplacedAllMulti {
            get {
                return ResourceManager.GetString("FindDialogMessageReplacedAllMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced the search term on {0} line..
        /// </summary>
        internal static string FindDialogMessageReplacedAllSingle {
            get {
                return ResourceManager.GetString("FindDialogMessageReplacedAllSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Replace with:.
        /// </summary>
        internal static string FindDialogReplaceWith {
            get {
                return ResourceManager.GetString("FindDialogReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string FindDialogTitleFind {
            get {
                return ResourceManager.GetString("FindDialogTitleFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string FindDialogTitleReplace {
            get {
                return ResourceManager.GetString("FindDialogTitleReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Use regular expression.
        /// </summary>
        internal static string FindDialogUseRegularExpression {
            get {
                return ResourceManager.GetString("FindDialogUseRegularExpression", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro buffer is empty..
        /// </summary>
        internal static string MacroBufferEmpty {
            get {
                return ResourceManager.GetString("MacroBufferEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macros (*.macro)|*.macro|All Files (*.*)|*.*.
        /// </summary>
        internal static string MacroDocumentsFilter {
            get {
                return ResourceManager.GetString("MacroDocumentsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .macro.
        /// </summary>
        internal static string MacroFileExtension {
            get {
                return ResourceManager.GetString("MacroFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load macro: {0}.
        /// </summary>
        internal static string MacroLoadError {
            get {
                return ResourceManager.GetString("MacroLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro loaded..
        /// </summary>
        internal static string MacroLoadOK {
            get {
                return ResourceManager.GetString("MacroLoadOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Macro.
        /// </summary>
        internal static string MacroLoadTitle {
            get {
                return ResourceManager.GetString("MacroLoadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro recording cancelled..
        /// </summary>
        internal static string MacroRecordCancelled {
            get {
                return ResourceManager.GetString("MacroRecordCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro recorded..
        /// </summary>
        internal static string MacroRecordEnd {
            get {
                return ResourceManager.GetString("MacroRecordEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording macro....
        /// </summary>
        internal static string MacroRecordStart {
            get {
                return ResourceManager.GetString("MacroRecordStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save macro: {0}.
        /// </summary>
        internal static string MacroSaveError {
            get {
                return ResourceManager.GetString("MacroSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro saved..
        /// </summary>
        internal static string MacroSaveOK {
            get {
                return ResourceManager.GetString("MacroSaveOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Macro.
        /// </summary>
        internal static string MacroSaveTitle {
            get {
                return ResourceManager.GetString("MacroSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string MainEditMenu {
            get {
                return ResourceManager.GetString("MainEditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad&amp;vanced.
        /// </summary>
        internal static string MainEditMenuAdvanced {
            get {
                return ResourceManager.GetString("MainEditMenuAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Block Comment.
        /// </summary>
        internal static string MainEditMenuBlockComment {
            get {
                return ResourceManager.GetString("MainEditMenuBlockComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Bookmarks.
        /// </summary>
        internal static string MainEditMenuBookmarks {
            get {
                return ResourceManager.GetString("MainEditMenuBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear All Bookmarks.
        /// </summary>
        internal static string MainEditMenuClearBookmarks {
            get {
                return ResourceManager.GetString("MainEditMenuClearBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Collapse All.
        /// </summary>
        internal static string MainEditMenuCollapseAll {
            get {
                return ResourceManager.GetString("MainEditMenuCollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        internal static string MainEditMenuCopy {
            get {
                return ResourceManager.GetString("MainEditMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu&amp;t.
        /// </summary>
        internal static string MainEditMenuCut {
            get {
                return ResourceManager.GetString("MainEditMenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Enc&amp;oding.
        /// </summary>
        internal static string MainEditMenuEncoding {
            get {
                return ResourceManager.GetString("MainEditMenuEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;ANSI.
        /// </summary>
        internal static string MainEditMenuEncodingANSI {
            get {
                return ResourceManager.GetString("MainEditMenuEncodingANSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTF-16 &amp;Big Endian.
        /// </summary>
        internal static string MainEditMenuEncodingUTF16BE {
            get {
                return ResourceManager.GetString("MainEditMenuEncodingUTF16BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTF-16 &amp;Little Endian.
        /// </summary>
        internal static string MainEditMenuEncodingUTF16LE {
            get {
                return ResourceManager.GetString("MainEditMenuEncodingUTF16LE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;UTF-8.
        /// </summary>
        internal static string MainEditMenuEncodingUTF8 {
            get {
                return ResourceManager.GetString("MainEditMenuEncodingUTF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Expand All.
        /// </summary>
        internal static string MainEditMenuExpandAll {
            get {
                return ResourceManager.GetString("MainEditMenuExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Find....
        /// </summary>
        internal static string MainEditMenuFind {
            get {
                return ResourceManager.GetString("MainEditMenuFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fo&amp;lding.
        /// </summary>
        internal static string MainEditMenuFolding {
            get {
                return ResourceManager.GetString("MainEditMenuFolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Go to Line....
        /// </summary>
        internal static string MainEditMenuGoTo {
            get {
                return ResourceManager.GetString("MainEditMenuGoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line &amp;Comment.
        /// </summary>
        internal static string MainEditMenuLineComment {
            get {
                return ResourceManager.GetString("MainEditMenuLineComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Ending St&amp;yle.
        /// </summary>
        internal static string MainEditMenuLineEnding {
            get {
                return ResourceManager.GetString("MainEditMenuLineEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Macintosh (CR).
        /// </summary>
        internal static string MainEditMenuLineEndingCR {
            get {
                return ResourceManager.GetString("MainEditMenuLineEndingCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Windows (CR LF).
        /// </summary>
        internal static string MainEditMenuLineEndingCRLF {
            get {
                return ResourceManager.GetString("MainEditMenuLineEndingCRLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Unix (LF).
        /// </summary>
        internal static string MainEditMenuLineEndingLF {
            get {
                return ResourceManager.GetString("MainEditMenuLineEndingLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Load Macro....
        /// </summary>
        internal static string MainEditMenuMacroLoad {
            get {
                return ResourceManager.GetString("MainEditMenuMacroLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Play Macro.
        /// </summary>
        internal static string MainEditMenuMacroPlay {
            get {
                return ResourceManager.GetString("MainEditMenuMacroPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Macros.
        /// </summary>
        internal static string MainEditMenuMacros {
            get {
                return ResourceManager.GetString("MainEditMenuMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save Macro....
        /// </summary>
        internal static string MainEditMenuMacroSave {
            get {
                return ResourceManager.GetString("MainEditMenuMacroSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Record Macro.
        /// </summary>
        internal static string MainEditMenuMacroStartRecord {
            get {
                return ResourceManager.GetString("MainEditMenuMacroStartRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Stop Recording.
        /// </summary>
        internal static string MainEditMenuMacroStopRecord {
            get {
                return ResourceManager.GetString("MainEditMenuMacroStopRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make &amp;Lowercase.
        /// </summary>
        internal static string MainEditMenuMakeLowercase {
            get {
                return ResourceManager.GetString("MainEditMenuMakeLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make &amp;Uppercase.
        /// </summary>
        internal static string MainEditMenuMakeUppercase {
            get {
                return ResourceManager.GetString("MainEditMenuMakeUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Manage Snippets....
        /// </summary>
        internal static string MainEditMenuManageSnippets {
            get {
                return ResourceManager.GetString("MainEditMenuManageSnippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next Bookmark.
        /// </summary>
        internal static string MainEditMenuNextBookmark {
            get {
                return ResourceManager.GetString("MainEditMenuNextBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        internal static string MainEditMenuPaste {
            get {
                return ResourceManager.GetString("MainEditMenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Previous Bookmark.
        /// </summary>
        internal static string MainEditMenuPreviousBookmark {
            get {
                return ResourceManager.GetString("MainEditMenuPreviousBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo.
        /// </summary>
        internal static string MainEditMenuRedo {
            get {
                return ResourceManager.GetString("MainEditMenuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;eplace....
        /// </summary>
        internal static string MainEditMenuReplace {
            get {
                return ResourceManager.GetString("MainEditMenuReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;All.
        /// </summary>
        internal static string MainEditMenuSelectAll {
            get {
                return ResourceManager.GetString("MainEditMenuSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set &amp;Read Only.
        /// </summary>
        internal static string MainEditMenuSetReadOnly {
            get {
                return ResourceManager.GetString("MainEditMenuSetReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Snippets.
        /// </summary>
        internal static string MainEditMenuSnippets {
            get {
                return ResourceManager.GetString("MainEditMenuSnippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Toggle Bookmark.
        /// </summary>
        internal static string MainEditMenuToggleBookmark {
            get {
                return ResourceManager.GetString("MainEditMenuToggleBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Toggle Fold.
        /// </summary>
        internal static string MainEditMenuToggleFold {
            get {
                return ResourceManager.GetString("MainEditMenuToggleFold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Trim Trailing White Space.
        /// </summary>
        internal static string MainEditMenuTrimWhitespace {
            get {
                return ResourceManager.GetString("MainEditMenuTrimWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        internal static string MainEditMenuUndo {
            get {
                return ResourceManager.GetString("MainEditMenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;White Space.
        /// </summary>
        internal static string MainEditMenuViewWhitespace {
            get {
                return ResourceManager.GetString("MainEditMenuViewWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W&amp;ord Wrap.
        /// </summary>
        internal static string MainEditMenuWordWrap {
            get {
                return ResourceManager.GetString("MainEditMenuWordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Set&amp;up....
        /// </summary>
        internal static string MainFileMenuPageSetup {
            get {
                return ResourceManager.GetString("MainFileMenuPageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print.
        /// </summary>
        internal static string MainFileMenuPrint {
            get {
                return ResourceManager.GetString("MainFileMenuPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;rint Preview.
        /// </summary>
        internal static string MainFileMenuPrintPreview {
            get {
                return ResourceManager.GetString("MainFileMenuPrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open snippets folder.
        /// </summary>
        internal static string ManageSnippetsErrorDialogText {
            get {
                return ResourceManager.GetString("ManageSnippetsErrorDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Snippets.
        /// </summary>
        internal static string ManageSnippetsErrorDialogTitle {
            get {
                return ResourceManager.GetString("ManageSnippetsErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrows.
        /// </summary>
        internal static string OptionsArrows {
            get {
                return ResourceManager.GetString("OptionsArrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bac&amp;kspace unindents.
        /// </summary>
        internal static string OptionsBackspaceUnindents {
            get {
                return ResourceManager.GetString("OptionsBackspaceUnindents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box plus minus.
        /// </summary>
        internal static string OptionsBoxPlusMinus {
            get {
                return ResourceManager.GetString("OptionsBoxPlusMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle plus minus.
        /// </summary>
        internal static string OptionsCirclePlusMinus {
            get {
                return ResourceManager.GetString("OptionsCirclePlusMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black on white.
        /// </summary>
        internal static string OptionsColorModeBlackOnWhite {
            get {
                return ResourceManager.GetString("OptionsColorModeBlackOnWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color on white.
        /// </summary>
        internal static string OptionsColorModeColorOnWhite {
            get {
                return ResourceManager.GetString("OptionsColorModeColorOnWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string OptionsColorModeNormal {
            get {
                return ResourceManager.GetString("OptionsColorModeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor settings.
        /// </summary>
        internal static string OptionsEditorSettings {
            get {
                return ResourceManager.GetString("OptionsEditorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold &amp;marker style:.
        /// </summary>
        internal static string OptionsFoldMarkerStyle {
            get {
                return ResourceManager.GetString("OptionsFoldMarkerStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold &amp;style:.
        /// </summary>
        internal static string OptionsFoldStyle {
            get {
                return ResourceManager.GetString("OptionsFoldStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Font:.
        /// </summary>
        internal static string OptionsFontName {
            get {
                return ResourceManager.GetString("OptionsFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global settings.
        /// </summary>
        internal static string OptionsGlobalSettings {
            get {
                return ResourceManager.GetString("OptionsGlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Editor.
        /// </summary>
        internal static string OptionsGroupText {
            get {
                return ResourceManager.GetString("OptionsGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hide file BOM.
        /// </summary>
        internal static string OptionsHideBOM {
            get {
                return ResourceManager.GetString("OptionsHideBOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line after contracted.
        /// </summary>
        internal static string OptionsLineAfterContracted {
            get {
                return ResourceManager.GetString("OptionsLineAfterContracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line before contracted.
        /// </summary>
        internal static string OptionsLineBeforeContracted {
            get {
                return ResourceManager.GetString("OptionsLineBeforeContracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Line number margin size:.
        /// </summary>
        internal static string OptionsLnMarginSize {
            get {
                return ResourceManager.GetString("OptionsLnMarginSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match &amp;braces.
        /// </summary>
        internal static string OptionsMatchBraces {
            get {
                return ResourceManager.GetString("OptionsMatchBraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string OptionsNone {
            get {
                return ResourceManager.GetString("OptionsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Allow these settings to override configuration files.
        /// </summary>
        internal static string OptionsOverrideConfigFiles {
            get {
                return ResourceManager.GetString("OptionsOverrideConfigFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor Settings.
        /// </summary>
        internal static string OptionsPageTextEditor {
            get {
                return ResourceManager.GetString("OptionsPageTextEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Settings.
        /// </summary>
        internal static string OptionsPageTextGlobal {
            get {
                return ResourceManager.GetString("OptionsPageTextGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus minus.
        /// </summary>
        internal static string OptionsPlusMinus {
            get {
                return ResourceManager.GetString("OptionsPlusMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Printing:.
        /// </summary>
        internal static string OptionsPrintingColorMode {
            get {
                return ResourceManager.GetString("OptionsPrintingColorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show fol&amp;ding.
        /// </summary>
        internal static string OptionsShowFolding {
            get {
                return ResourceManager.GetString("OptionsShowFolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show indentation &amp;guides.
        /// </summary>
        internal static string OptionsShowIndentationGuides {
            get {
                return ResourceManager.GetString("OptionsShowIndentationGuides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tab size:.
        /// </summary>
        internal static string OptionsTabSize {
            get {
                return ResourceManager.GetString("OptionsTabSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Use tabs.
        /// </summary>
        internal static string OptionsUseTabs {
            get {
                return ResourceManager.GetString("OptionsUseTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Word wrap.
        /// </summary>
        internal static string OptionsWordWrap {
            get {
                return ResourceManager.GetString("OptionsWordWrap", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PageSetup {
            get {
                object obj = ResourceManager.GetObject("PageSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Print {
            get {
                object obj = ResourceManager.GetObject("Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing.
        /// </summary>
        internal static string PrintErrorTitle {
            get {
                return ResourceManager.GetString("PrintErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an editable version of this file already available..
        /// </summary>
        internal static string ReadWriteMessage {
            get {
                return ResourceManager.GetString("ReadWriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Read Only.
        /// </summary>
        internal static string ReadWriteTitle {
            get {
                return ResourceManager.GetString("ReadWriteTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Redo {
            get {
                object obj = ResourceManager.GetObject("Redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has changed. Save the changes?.
        /// </summary>
        internal static string SaveChangesMessage {
            get {
                return ResourceManager.GetString("SaveChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string SaveChangesTitle {
            get {
                return ResourceManager.GetString("SaveChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save:.
        /// </summary>
        internal static string SaveErrorMessage {
            get {
                return ResourceManager.GetString("SaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveErrorTitle {
            get {
                return ResourceManager.GetString("SaveErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only.
        /// </summary>
        internal static string TabReadOnly {
            get {
                return ResourceManager.GetString("TabReadOnly", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Undo {
            get {
                object obj = ResourceManager.GetObject("Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
