//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSharp.CodeAssist.DotNet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickSharp.CodeAssist.DotNet.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Files (*.dll)|*.dll|All Files (*.*)|*.*.
        /// </summary>
        internal static string AddFileDialogFilter {
            get {
                return ResourceManager.GetString("AddFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Namespaces from Assembly.
        /// </summary>
        internal static string AddFileDialogTitle {
            get {
                return ResourceManager.GetString("AddFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add namespaces from assemblies in a folder..
        /// </summary>
        internal static string AddFolderDialogText {
            get {
                return ResourceManager.GetString("AddFolderDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the Code Assist reference database is initialized from the .NET Global Assembly Cache....
        /// </summary>
        internal static string CreateDbDialogMessage {
            get {
                return ResourceManager.GetString("CreateDbDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Assist.
        /// </summary>
        internal static string CreateDbDialogTitle {
            get {
                return ResourceManager.GetString("CreateDbDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize the Code Assist reference database.
        /// </summary>
        internal static string CreateDbErrorMessage {
            get {
                return ResourceManager.GetString("CreateDbErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string CreateDbErrorTitle {
            get {
                return ResourceManager.GetString("CreateDbErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Enable.
        /// </summary>
        internal static string OptionsColorize {
            get {
                return ResourceManager.GetString("OptionsColorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorize types and variables.
        /// </summary>
        internal static string OptionsColorizeGroupBox {
            get {
                return ResourceManager.GetString("OptionsColorizeGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorize on &amp;activation.
        /// </summary>
        internal static string OptionsColorizeOnActivate {
            get {
                return ResourceManager.GetString("OptionsColorizeOnActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorize on loo&amp;kup.
        /// </summary>
        internal static string OptionsColorizeOnLookup {
            get {
                return ResourceManager.GetString("OptionsColorizeOnLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include &amp;types.
        /// </summary>
        internal static string OptionsColorizeTypes {
            get {
                return ResourceManager.GetString("OptionsColorizeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include &amp;variables.
        /// </summary>
        internal static string OptionsColorizeVariables {
            get {
                return ResourceManager.GetString("OptionsColorizeVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include &amp;global assemblies.
        /// </summary>
        internal static string OptionsGlobalAssemblies {
            get {
                return ResourceManager.GetString("OptionsGlobalAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Assist.
        /// </summary>
        internal static string OptionsGroupText {
            get {
                return ResourceManager.GetString("OptionsGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Manage.
        /// </summary>
        internal static string OptionsManageNamespacesButton {
            get {
                return ResourceManager.GetString("OptionsManageNamespacesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET.
        /// </summary>
        internal static string OptionsPageText {
            get {
                return ResourceManager.GetString("OptionsPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference namespaces.
        /// </summary>
        internal static string OptionsReferenceGroupBox {
            get {
                return ResourceManager.GetString("OptionsReferenceGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reload.
        /// </summary>
        internal static string OptionsReloadNamespacesButton {
            get {
                return ResourceManager.GetString("OptionsReloadNamespacesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading the reference database will delete any namespace.
        /// </summary>
        internal static string OptionsReloadWarningMessage1 {
            get {
                return ResourceManager.GetString("OptionsReloadWarningMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to references you have added manually. Continue?.
        /// </summary>
        internal static string OptionsReloadWarningMessage2 {
            get {
                return ResourceManager.GetString("OptionsReloadWarningMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Namespaces.
        /// </summary>
        internal static string OptionsReloadWarningTitle {
            get {
                return ResourceManager.GetString("OptionsReloadWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read the Code Assist reference database.
        /// </summary>
        internal static string ReadDbErrorMessage {
            get {
                return ResourceManager.GetString("ReadDbErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ReadDbErrorTitle {
            get {
                return ResourceManager.GetString("ReadDbErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File....
        /// </summary>
        internal static string ReferencesFormAddFile {
            get {
                return ResourceManager.GetString("ReferencesFormAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder....
        /// </summary>
        internal static string ReferencesFormAddFolder {
            get {
                return ResourceManager.GetString("ReferencesFormAddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ReferencesFormCancel {
            get {
                return ResourceManager.GetString("ReferencesFormCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ReferencesFormOK {
            get {
                return ResourceManager.GetString("ReferencesFormOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string ReferencesFormReload {
            get {
                return ResourceManager.GetString("ReferencesFormReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Reference Namespaces.
        /// </summary>
        internal static string ReferencesFormTitle {
            get {
                return ResourceManager.GetString("ReferencesFormTitle", resourceCulture);
            }
        }
    }
}
