//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSharp.BuildTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickSharp.BuildTools.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build completed with errors.
        /// </summary>
        internal static string BuildErrors {
            get {
                return ResourceManager.GetString("BuildErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build halted.
        /// </summary>
        internal static string BuildHalted {
            get {
                return ResourceManager.GetString("BuildHalted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build started....
        /// </summary>
        internal static string BuildStarted {
            get {
                return ResourceManager.GetString("BuildStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build completed successfully.
        /// </summary>
        internal static string BuildSuccess {
            get {
                return ResourceManager.GetString("BuildSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of {0}.
        /// </summary>
        internal static string CloneCopyName {
            get {
                return ResourceManager.GetString("CloneCopyName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Compile {
            get {
                object obj = ResourceManager.GetObject("Compile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to build tool is invalid.
        /// </summary>
        internal static string ErrorBuildToolInvalid {
            get {
                return ResourceManager.GetString("ErrorBuildToolInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no build tool for the file.
        /// </summary>
        internal static string ErrorBuildToolNotFound {
            get {
                return ResourceManager.GetString("ErrorBuildToolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filename is invalid.
        /// </summary>
        internal static string ErrorFilenameInvalid {
            get {
                return ResourceManager.GetString("ErrorFilenameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file not found.
        /// </summary>
        internal static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source file is invalid.
        /// </summary>
        internal static string ErrorSourceInvalid {
            get {
                return ResourceManager.GetString("ErrorSourceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Compile.
        /// </summary>
        internal static string MainToolsMenuCompile {
            get {
                return ResourceManager.GetString("MainToolsMenuCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile &amp;All.
        /// </summary>
        internal static string MainToolsMenuCompileAll {
            get {
                return ResourceManager.GetString("MainToolsMenuCompileAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Run.
        /// </summary>
        internal static string MainToolsMenuRun {
            get {
                return ResourceManager.GetString("MainToolsMenuRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always build dependencies on &amp;Compile.
        /// </summary>
        internal static string OptionsAlwaysBuildOnCompile {
            get {
                return ResourceManager.GetString("OptionsAlwaysBuildOnCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always build dependencies on &amp;Run.
        /// </summary>
        internal static string OptionsAlwaysBuildOnRun {
            get {
                return ResourceManager.GetString("OptionsAlwaysBuildOnRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Tools.
        /// </summary>
        internal static string OptionsGroupText {
            get {
                return ResourceManager.GetString("OptionsGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Settings.
        /// </summary>
        internal static string OptionsPageTextSettings {
            get {
                return ResourceManager.GetString("OptionsPageTextSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Settings.
        /// </summary>
        internal static string OptionsPageTextTools {
            get {
                return ResourceManager.GetString("OptionsPageTextTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output - Compile:.
        /// </summary>
        internal static string OutputWindowCompile {
            get {
                return ResourceManager.GetString("OutputWindowCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output - Run:.
        /// </summary>
        internal static string OutputWindowRun {
            get {
                return ResourceManager.GetString("OutputWindowRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ParserListNone {
            get {
                return ResourceManager.GetString("ParserListNone", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Pin {
            get {
                object obj = ResourceManager.GetObject("Pin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-compile task:.
        /// </summary>
        internal static string PostCompileTask {
            get {
                return ResourceManager.GetString("PostCompileTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-run task:.
        /// </summary>
        internal static string PostRunTask {
            get {
                return ResourceManager.GetString("PostRunTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-compile task:.
        /// </summary>
        internal static string PreCompileTask {
            get {
                return ResourceManager.GetString("PreCompileTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-run task:.
        /// </summary>
        internal static string PreRunTask {
            get {
                return ResourceManager.GetString("PreRunTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target ({0}) is not executable.
        /// </summary>
        internal static string ProgramNotExecutable {
            get {
                return ResourceManager.GetString("ProgramNotExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program returned {0}.
        /// </summary>
        internal static string ProgramReturn {
            get {
                return ResourceManager.GetString("ProgramReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------ {0}.
        /// </summary>
        internal static string ProgramTarget {
            get {
                return ResourceManager.GetString("ProgramTarget", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Run {
            get {
                object obj = ResourceManager.GetObject("Run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable files (*.exe)|*.exe|All Files (*.*)|*.*.
        /// </summary>
        internal static string SelectFileDialogFilter {
            get {
                return ResourceManager.GetString("SelectFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        internal static string SelectFileDialogTitle {
            get {
                return ResourceManager.GetString("SelectFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile (Shift+F5).
        /// </summary>
        internal static string ToolbarCompile {
            get {
                return ResourceManager.GetString("ToolbarCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinned File.
        /// </summary>
        internal static string ToolbarPinFile {
            get {
                return ResourceManager.GetString("ToolbarPinFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run (Ctrl+F5).
        /// </summary>
        internal static string ToolbarRun {
            get {
                return ResourceManager.GetString("ToolbarRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string ToolColumnAction {
            get {
                return ResourceManager.GetString("ToolColumnAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ToolColumnName {
            get {
                return ResourceManager.GetString("ToolColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ToolColumnType {
            get {
                return ResourceManager.GetString("ToolColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}?.
        /// </summary>
        internal static string ToolDeleteMessage {
            get {
                return ResourceManager.GetString("ToolDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ToolDeleteTitle {
            get {
                return ResourceManager.GetString("ToolDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&amp;ction:.
        /// </summary>
        internal static string ToolDialogAction {
            get {
                return ResourceManager.GetString("ToolDialogAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Arguments:.
        /// </summary>
        internal static string ToolDialogArguments {
            get {
                return ResourceManager.GetString("ToolDialogArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ToolDialogCancel {
            get {
                return ResourceManager.GetString("ToolDialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common &amp;options:.
        /// </summary>
        internal static string ToolDialogCommonOptions {
            get {
                return ResourceManager.GetString("ToolDialogCommonOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display &amp;name:.
        /// </summary>
        internal static string ToolDialogDisplayName {
            get {
                return ResourceManager.GetString("ToolDialogDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &amp;type:.
        /// </summary>
        internal static string ToolDialogFileType {
            get {
                return ResourceManager.GetString("ToolDialogFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ToolDialogOK {
            get {
                return ResourceManager.GetString("ToolDialogOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output par&amp;ser:.
        /// </summary>
        internal static string ToolDialogOutputParser {
            get {
                return ResourceManager.GetString("ToolDialogOutputParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Path:.
        /// </summary>
        internal static string ToolDialogPath {
            get {
                return ResourceManager.GetString("ToolDialogPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Tool.
        /// </summary>
        internal static string ToolDialogTitle {
            get {
                return ResourceManager.GetString("ToolDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clone.
        /// </summary>
        internal static string ToolMenuClone {
            get {
                return ResourceManager.GetString("ToolMenuClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string ToolMenuDelete {
            get {
                return ResourceManager.GetString("ToolMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit....
        /// </summary>
        internal static string ToolMenuEdit {
            get {
                return ResourceManager.GetString("ToolMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New....
        /// </summary>
        internal static string ToolMenuNew {
            get {
                return ResourceManager.GetString("ToolMenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show source files only.
        /// </summary>
        internal static string WorkspaceShowSourceOnly {
            get {
                return ResourceManager.GetString("WorkspaceShowSourceOnly", resourceCulture);
            }
        }
    }
}
