//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSharp.SqlManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickSharp.SqlManager.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of {0}.
        /// </summary>
        internal static string ConnectionCloneNewName {
            get {
                return ResourceManager.GetString("ConnectionCloneNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}?.
        /// </summary>
        internal static string ConnectionDeleteMessage {
            get {
                return ResourceManager.GetString("ConnectionDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ConnectionDeleteTitle {
            get {
                return ResourceManager.GetString("ConnectionDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data provider selected..
        /// </summary>
        internal static string ConnectionInvalidProvider {
            get {
                return ResourceManager.GetString("ConnectionInvalidProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection failed.
        /// </summary>
        internal static string ConnectionTestFailure {
            get {
                return ResourceManager.GetString("ConnectionTestFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection string was provided..
        /// </summary>
        internal static string ConnectionTestNoString {
            get {
                return ResourceManager.GetString("ConnectionTestNoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection was successful..
        /// </summary>
        internal static string ConnectionTestSuccess {
            get {
                return ResourceManager.GetString("ConnectionTestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        internal static string ConnectionTestTitle {
            get {
                return ResourceManager.GetString("ConnectionTestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        internal static string ContextMenuClone {
            get {
                return ResourceManager.GetString("ContextMenuClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ContextMenuDelete {
            get {
                return ResourceManager.GetString("ContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit....
        /// </summary>
        internal static string ContextMenuEdit {
            get {
                return ResourceManager.GetString("ContextMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        internal static string ContextMenuNew {
            get {
                return ResourceManager.GetString("ContextMenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database file not found.
        /// </summary>
        internal static string DbFileNotFoundMessage {
            get {
                return ResourceManager.GetString("DbFileNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate DBML.
        /// </summary>
        internal static string DbFileNotFoundTitle {
            get {
                return ResourceManager.GetString("DbFileNotFoundTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ExtractDbml {
            get {
                object obj = ResourceManager.GetObject("ExtractDbml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string FormButtonCancel {
            get {
                return ResourceManager.GetString("FormButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string FormButtonOK {
            get {
                return ResourceManager.GetString("FormButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        internal static string FormButtonTest {
            get {
                return ResourceManager.GetString("FormButtonTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Connection string:.
        /// </summary>
        internal static string FormConnectionString {
            get {
                return ResourceManager.GetString("FormConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Name:.
        /// </summary>
        internal static string FormName {
            get {
                return ResourceManager.GetString("FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Provider:.
        /// </summary>
        internal static string FormProvider {
            get {
                return ResourceManager.GetString("FormProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Connection.
        /// </summary>
        internal static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ListColumnName {
            get {
                return ResourceManager.GetString("ListColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run &amp;SQL Query.
        /// </summary>
        internal static string MainToolsMenuRunQuery {
            get {
                return ResourceManager.GetString("MainToolsMenuRunQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Manager.
        /// </summary>
        internal static string OptionsGroupText {
            get {
                return ResourceManager.GetString("OptionsGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        internal static string OptionsPageTextConnections {
            get {
                return ResourceManager.GetString("OptionsPageTextConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlMetal Utility.
        /// </summary>
        internal static string OptionsPageTextSqlMetal {
            get {
                return ResourceManager.GetString("OptionsPageTextSqlMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output - Run SQL Query.
        /// </summary>
        internal static string OutputWindowRunQuery {
            get {
                return ResourceManager.GetString("OutputWindowRunQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output - Extract DBML.
        /// </summary>
        internal static string OutputWindowRunSqlMetal {
            get {
                return ResourceManager.GetString("OutputWindowRunSqlMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin transaction.
        /// </summary>
        internal static string QueryBeginTransaction {
            get {
                return ResourceManager.GetString("QueryBeginTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commit transaction.
        /// </summary>
        internal static string QueryCommitTransaction {
            get {
                return ResourceManager.GetString("QueryCommitTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query complete.
        /// </summary>
        internal static string QueryComplete {
            get {
                return ResourceManager.GetString("QueryComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable{0}_Row.
        /// </summary>
        internal static string QueryDataRowName {
            get {
                return ResourceManager.GetString("QueryDataRowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSet.
        /// </summary>
        internal static string QueryDataSetName {
            get {
                return ResourceManager.GetString("QueryDataSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} command completed with errors: {1}.
        /// </summary>
        internal static string QueryErrors {
            get {
                return ResourceManager.GetString("QueryErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} command completed successfully: {1} {2} affected.
        /// </summary>
        internal static string QueryNonSelectSuccess {
            get {
                return ResourceManager.GetString("QueryNonSelectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rollback transaction.
        /// </summary>
        internal static string QueryRollbackTransaction {
            get {
                return ResourceManager.GetString("QueryRollbackTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rows.
        /// </summary>
        internal static string QueryRowPlural {
            get {
                return ResourceManager.GetString("QueryRowPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to row.
        /// </summary>
        internal static string QueryRowSingular {
            get {
                return ResourceManager.GetString("QueryRowSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        internal static string QuerySelectCommand {
            get {
                return ResourceManager.GetString("QuerySelectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} command completed successfully: {1} {2} returned.
        /// </summary>
        internal static string QuerySelectSuccess {
            get {
                return ResourceManager.GetString("QuerySelectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query started.
        /// </summary>
        internal static string QueryStarted {
            get {
                return ResourceManager.GetString("QueryStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sql.
        /// </summary>
        internal static string QueryUnknownCommand {
            get {
                return ResourceManager.GetString("QueryUnknownCommand", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap RunQuery {
            get {
                object obj = ResourceManager.GetObject("RunQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SqlConnection {
            get {
                object obj = ResourceManager.GetObject("SqlConnection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML extract complete.
        /// </summary>
        internal static string SqlMetalComplete {
            get {
                return ResourceManager.GetString("SqlMetalComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure SqlMetal.
        /// </summary>
        internal static string SqlMetalConfigTitle {
            get {
                return ResourceManager.GetString("SqlMetalConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string SqlMetalFormCancel {
            get {
                return ResourceManager.GetString("SqlMetalFormCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Output filename:.
        /// </summary>
        internal static string SqlMetalFormFilename {
            get {
                return ResourceManager.GetString("SqlMetalFormFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Functions.
        /// </summary>
        internal static string SqlMetalFormFunctions {
            get {
                return ResourceManager.GetString("SqlMetalFormFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include.
        /// </summary>
        internal static string SqlMetalFormIncludeGroup {
            get {
                return ResourceManager.GetString("SqlMetalFormIncludeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Database Markup Language file from the database.
        /// </summary>
        internal static string SqlMetalFormIntro {
            get {
                return ResourceManager.GetString("SqlMetalFormIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlMetal tool not found, use the Options editor to set the path..
        /// </summary>
        internal static string SqlMetalFormNoTool {
            get {
                return ResourceManager.GetString("SqlMetalFormNoTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string SqlMetalFormOk {
            get {
                return ResourceManager.GetString("SqlMetalFormOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Stored procedures.
        /// </summary>
        internal static string SqlMetalFormSprocs {
            get {
                return ResourceManager.GetString("SqlMetalFormSprocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract DBML File.
        /// </summary>
        internal static string SqlMetalFormTitle {
            get {
                return ResourceManager.GetString("SqlMetalFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Views.
        /// </summary>
        internal static string SqlMetalFormViews {
            get {
                return ResourceManager.GetString("SqlMetalFormViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwite existing file: {0}?.
        /// </summary>
        internal static string SqlMetalOverwriteMessage {
            get {
                return ResourceManager.GetString("SqlMetalOverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate DBML.
        /// </summary>
        internal static string SqlMetalOverwriteTitle {
            get {
                return ResourceManager.GetString("SqlMetalOverwriteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML extract started.
        /// </summary>
        internal static string SqlMetalStarted {
            get {
                return ResourceManager.GetString("SqlMetalStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Path to SqlMetal utility:.
        /// </summary>
        internal static string SqlMetalToolPath {
            get {
                return ResourceManager.GetString("SqlMetalToolPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: the saved path does not exist..
        /// </summary>
        internal static string SqlMetalToolPathWarning {
            get {
                return ResourceManager.GetString("SqlMetalToolPathWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML extract completed.
        /// </summary>
        internal static string StatusBarExtractCompleted {
            get {
                return ResourceManager.GetString("StatusBarExtractCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBML extract started....
        /// </summary>
        internal static string StatusBarExtractStarted {
            get {
                return ResourceManager.GetString("StatusBarExtractStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query completed with errors.
        /// </summary>
        internal static string StatusBarQueryError {
            get {
                return ResourceManager.GetString("StatusBarQueryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query started....
        /// </summary>
        internal static string StatusBarQueryStarted {
            get {
                return ResourceManager.GetString("StatusBarQueryStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query completed successfully.
        /// </summary>
        internal static string StatusBarQuerySuccess {
            get {
                return ResourceManager.GetString("StatusBarQuerySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Connection.
        /// </summary>
        internal static string ToolbarActivateConnection {
            get {
                return ResourceManager.GetString("ToolbarActivateConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Connection.
        /// </summary>
        internal static string ToolbarActiveConnection {
            get {
                return ResourceManager.GetString("ToolbarActiveConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLConnection.
        /// </summary>
        internal static string ToolbarSqlConnection {
            get {
                return ResourceManager.GetString("ToolbarSqlConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract DBML File.
        /// </summary>
        internal static string ToolbarSqlExtractDbml {
            get {
                return ResourceManager.GetString("ToolbarSqlExtractDbml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run SQL Query (F5).
        /// </summary>
        internal static string ToolbarSqlRunQuery {
            get {
                return ResourceManager.GetString("ToolbarSqlRunQuery", resourceCulture);
            }
        }
    }
}
