//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSharp.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickSharp.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AboutButtonOK {
            get {
                return ResourceManager.GetString("AboutButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickSharp.Core Version.
        /// </summary>
        internal static string AboutCopyright1 {
            get {
                return ResourceManager.GetString("AboutCopyright1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2008-2011 Steve Walker.
        /// </summary>
        internal static string AboutCopyright2 {
            get {
                return ResourceManager.GetString("AboutCopyright2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://quicksharp.sourceforge.net.
        /// </summary>
        internal static string AboutCopyright3 {
            get {
                return ResourceManager.GetString("AboutCopyright3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DockPanelSuite Copyright © 2007 Weifen Luo.
        /// </summary>
        internal static string AboutCopyrightDPS1 {
            get {
                return ResourceManager.GetString("AboutCopyrightDPS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://sourceforge.net/projects/dockpanelsuite.
        /// </summary>
        internal static string AboutCopyrightDPS2 {
            get {
                return ResourceManager.GetString("AboutCopyrightDPS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string AboutDependenciesNone {
            get {
                return ResourceManager.GetString("AboutDependenciesNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed plugins:.
        /// </summary>
        internal static string AboutInstalledPlugins {
            get {
                return ResourceManager.GetString("AboutInstalledPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin details:.
        /// </summary>
        internal static string AboutPluginDetails {
            get {
                return ResourceManager.GetString("AboutPluginDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required by.
        /// </summary>
        internal static string AboutRequiredBy {
            get {
                return ResourceManager.GetString("AboutRequiredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires.
        /// </summary>
        internal static string AboutRequires {
            get {
                return ResourceManager.GetString("AboutRequires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*.
        /// </summary>
        internal static string AllDocumentsFilter {
            get {
                return ResourceManager.GetString("AllDocumentsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string ErrorButtonContinue {
            get {
                return ResourceManager.GetString("ErrorButtonContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string ErrorButtonQuit {
            get {
                return ResourceManager.GetString("ErrorButtonQuit", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon ErrorFormIcon {
            get {
                object obj = ResourceManager.GetObject("ErrorFormIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred:.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack trace:.
        /// </summary>
        internal static string ErrorStackTrace {
            get {
                return ResourceManager.GetString("ErrorStackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FullScreen {
            get {
                object obj = ResourceManager.GetObject("FullScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open help file.
        /// </summary>
        internal static string HelpOpenErrorMessage {
            get {
                return ResourceManager.GetString("HelpOpenErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpOpenErrorTitle {
            get {
                return ResourceManager.GetString("HelpOpenErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required configuration file is invalid and has been deleted. Please restart the application..
        /// </summary>
        internal static string InvalidDockConfigMessage {
            get {
                return ResourceManager.GetString("InvalidDockConfigMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string MainFileMenu {
            get {
                return ResourceManager.GetString("MainFileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string MainFileMenuExit {
            get {
                return ResourceManager.GetString("MainFileMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        internal static string MainFileMenuNew {
            get {
                return ResourceManager.GetString("MainFileMenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open....
        /// </summary>
        internal static string MainFileMenuOpen {
            get {
                return ResourceManager.GetString("MainFileMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent &amp;Files.
        /// </summary>
        internal static string MainFileMenuRecentFiles {
            get {
                return ResourceManager.GetString("MainFileMenuRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string MainFileMenuSave {
            get {
                return ResourceManager.GetString("MainFileMenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save A&amp;ll....
        /// </summary>
        internal static string MainFileMenuSaveAll {
            get {
                return ResourceManager.GetString("MainFileMenuSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;As....
        /// </summary>
        internal static string MainFileMenuSaveAs {
            get {
                return ResourceManager.GetString("MainFileMenuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string MainHelpMenu {
            get {
                return ResourceManager.GetString("MainHelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        internal static string MainHelpMenuAbout {
            get {
                return ResourceManager.GetString("MainHelpMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chec&amp;k for Updates.
        /// </summary>
        internal static string MainHelpMenuCheckForUpdates {
            get {
                return ResourceManager.GetString("MainHelpMenuCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New (Ctrl+N).
        /// </summary>
        internal static string MainToolbarNew {
            get {
                return ResourceManager.GetString("MainToolbarNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open (Ctrl+O).
        /// </summary>
        internal static string MainToolbarOpen {
            get {
                return ResourceManager.GetString("MainToolbarOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save (Ctrl+S).
        /// </summary>
        internal static string MainToolbarSave {
            get {
                return ResourceManager.GetString("MainToolbarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All (Ctrl+Shft+S).
        /// </summary>
        internal static string MainToolbarSaveAll {
            get {
                return ResourceManager.GetString("MainToolbarSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string MainToolbarText {
            get {
                return ResourceManager.GetString("MainToolbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string MainToolsMenu {
            get {
                return ResourceManager.GetString("MainToolsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options....
        /// </summary>
        internal static string MainToolsMenuOptions {
            get {
                return ResourceManager.GetString("MainToolsMenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string MainViewMenu {
            get {
                return ResourceManager.GetString("MainViewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Full Screen.
        /// </summary>
        internal static string MainViewMenuFullScreen {
            get {
                return ResourceManager.GetString("MainViewMenuFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Status Bar.
        /// </summary>
        internal static string MainViewMenuStatusBar {
            get {
                return ResourceManager.GetString("MainViewMenuStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Toolbars.
        /// </summary>
        internal static string MainViewMenuToolbarMulti {
            get {
                return ResourceManager.GetString("MainViewMenuToolbarMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Toolbar.
        /// </summary>
        internal static string MainViewMenuToolbarSingle {
            get {
                return ResourceManager.GetString("MainViewMenuToolbarSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Window.
        /// </summary>
        internal static string MainWindowMenu {
            get {
                return ResourceManager.GetString("MainWindowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string MainWindowMenuClose {
            get {
                return ResourceManager.GetString("MainWindowMenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close &amp;All.
        /// </summary>
        internal static string MainWindowMenuCloseAll {
            get {
                return ResourceManager.GetString("MainWindowMenuCloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All &amp;But Active.
        /// </summary>
        internal static string MainWindowMenuCloseAllButActive {
            get {
                return ResourceManager.GetString("MainWindowMenuCloseAllButActive", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap New {
            get {
                object obj = ResourceManager.GetObject("New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No handler has been defined for this type of file..
        /// </summary>
        internal static string NoHandlerMessage {
            get {
                return ResourceManager.GetString("NoHandlerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string NoHandlerTitle {
            get {
                return ResourceManager.GetString("NoHandlerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientProfile cannot be null.
        /// </summary>
        internal static string NullClientProfileMessage {
            get {
                return ResourceManager.GetString("NullClientProfileMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow documents to be opened using &amp;Windows shell associations.
        /// </summary>
        internal static string OptionsAllowShellOpen {
            get {
                return ResourceManager.GetString("OptionsAllowShellOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string OptionsButtonCancel {
            get {
                return ResourceManager.GetString("OptionsButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OptionsButtonOK {
            get {
                return ResourceManager.GetString("OptionsButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document handling.
        /// </summary>
        internal static string OptionsDocumentsGroupBox {
            get {
                return ResourceManager.GetString("OptionsDocumentsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string OptionsGroupText {
            get {
                return ResourceManager.GetString("OptionsGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Settings.
        /// </summary>
        internal static string OptionsPageTextGeneral {
            get {
                return ResourceManager.GetString("OptionsPageTextGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the application to apply the settings on this page.
        /// </summary>
        internal static string OptionsRestartRequired {
            get {
                return ResourceManager.GetString("OptionsRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Restore documents from the previous session.
        /// </summary>
        internal static string OptionsRestoreLastSession {
            get {
                return ResourceManager.GetString("OptionsRestoreLastSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;document paths in status bar.
        /// </summary>
        internal static string OptionsShowDocumentPath {
            get {
                return ResourceManager.GetString("OptionsShowDocumentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Show a message when no document handler is available.
        /// </summary>
        internal static string OptionsShowNoHandler {
            get {
                return ResourceManager.GetString("OptionsShowNoHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string OptionsThemeGroupBox {
            get {
                return ResourceManager.GetString("OptionsThemeGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string OptionsTitle {
            get {
                return ResourceManager.GetString("OptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load plugin: &quot;{0}&quot;. Check for missing plugin dependencies and/or referenced assemblies..
        /// </summary>
        internal static string PluginDependencyError0 {
            get {
                return ResourceManager.GetString("PluginDependencyError0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsatisifed plugin dependency: &quot;{0}&quot; requires &quot;{1}&quot;..
        /// </summary>
        internal static string PluginDependencyError1 {
            get {
                return ResourceManager.GetString("PluginDependencyError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsatisifed plugin dependency: &quot;{0}&quot; requires &quot;{1}&quot; to be of version {2} or higher, found plugin with version {3}..
        /// </summary>
        internal static string PluginDependencyError2 {
            get {
                return ResourceManager.GetString("PluginDependencyError2", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaveAll {
            get {
                object obj = ResourceManager.GetObject("SaveAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clean.
        /// </summary>
        internal static string SwitchClean {
            get {
                return ResourceManager.GetString("SwitchClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Operating System Theme.
        /// </summary>
        internal static string ThemeDefault {
            get {
                return ResourceManager.GetString("ThemeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio 2008 Theme.
        /// </summary>
        internal static string ThemeVS2008 {
            get {
                return ResourceManager.GetString("ThemeVS2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio 2010 Theme (Basic).
        /// </summary>
        internal static string ThemeVS2010Basic {
            get {
                return ResourceManager.GetString("ThemeVS2010Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio 2010 Theme.
        /// </summary>
        internal static string ThemeVS2010Enhanced {
            get {
                return ResourceManager.GetString("ThemeVS2010Enhanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string UpdateButtonCancel {
            get {
                return ResourceManager.GetString("UpdateButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Now.
        /// </summary>
        internal static string UpdateButtonCheck {
            get {
                return ResourceManager.GetString("UpdateButtonCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string UpdateButtonClose {
            get {
                return ResourceManager.GetString("UpdateButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the link.
        /// </summary>
        internal static string UpdateCheckLinkErrorMessage {
            get {
                return ResourceManager.GetString("UpdateCheckLinkErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Error.
        /// </summary>
        internal static string UpdateCheckLinkErrorTitle {
            get {
                return ResourceManager.GetString("UpdateCheckLinkErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get the latest version, check was cancelled..
        /// </summary>
        internal static string UpdateMessageCheckCancelled {
            get {
                return ResourceManager.GetString("UpdateMessageCheckCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get the latest version, please try again later..
        /// </summary>
        internal static string UpdateMessageCheckFailed {
            get {
                return ResourceManager.GetString("UpdateMessageCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates, please wait....
        /// </summary>
        internal static string UpdateMessageChecking {
            get {
                return ResourceManager.GetString("UpdateMessageChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Check Now&apos; to check for updates..
        /// </summary>
        internal static string UpdateMessageCheckNow {
            get {
                return ResourceManager.GetString("UpdateMessageCheckNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running version {0}.
        /// </summary>
        internal static string UpdateMessageCurrentVersion {
            get {
                return ResourceManager.GetString("UpdateMessageCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest version is {0}.
        /// </summary>
        internal static string UpdateMessageLatestVersion {
            get {
                return ResourceManager.GetString("UpdateMessageLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap VS2010ThemeBackground {
            get {
                object obj = ResourceManager.GetObject("VS2010ThemeBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VS2010ThemeMenuBackground {
            get {
                object obj = ResourceManager.GetObject("VS2010ThemeMenuBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VS2010ThemeToolbarBackground {
            get {
                object obj = ResourceManager.GetObject("VS2010ThemeToolbarBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
